class Configuration(object):

	K_NORTH =			273 # haut
	K_SOUTH =			274 # bas
	K_LEFT =			276 # gauche
	K_RIGHT =			275 # droite
	K_STIFFON =			270 # +
	K_STIFFOFF =		269 # -
	K_SAVE_JOINTS =		115 # s
	K_PLAY_JOINTS =		112 # p
	K_RECORD =			114 # r
	K_CROUCH =			97  # a
	K_SITDOWN =			108 # l
	K_STANDUP =			109 # m
	K_QUIT =			113 # q

	J_INDEX =			0
	J_BUTTON_A =		0	# s'assoir
	J_BUTTON_B =		1	# se lever
	J_BUTTON_SAVE =		5	# enregistrer une position
	J_BUTTON_RECORD =	6	# enregistrer dans le temps
	J_BUTTON_PLAY =		4	# jouer enregistrement
	J_BUTTON_STIFF =	2	# permuter stiffness
	J_BUTTON_LASTPOSE =	3	# se mettre dans la derniere pose enregistree
	J_AXIS_WE =			0
	J_AXIS_NS =			1
	J_AXIS_ROT =		2
	J_INTERVAL_W =		[-2.0, -0.5]
	J_INTERVAL_E =		[+0.5, +2.0]
	J_INTERVAL_0WE =	[-0.3, +0.3]
	J_INTERVAL_N =		[-2.0, -0.5]
	J_INTERVAL_S =		[+0.5, +2.0]
	J_INTERVAL_0NS =	[-0.3, +0.3]
	J_INTERVAL_L =		[-2.0, -0.9]
	J_INTERVAL_R =		[+0.9, +2.0]
	J_INTERVAL_0ROT =	[-0.7, +0.7]
	J_HAT_HEAD =		0
	J_HAT_0 =			(+0, +0)
	J_HAT_N =			(+0, +1)
	J_HAT_S =			(+0, -1)
	J_HAT_W =			(-1, +0)
	J_HAT_E =			(+1, +0)
	J_HAT_NE =			(+1, +1)
	J_HAT_SE =			(+1, -1)
	J_HAT_SW =			(-1, -1)
	J_HAT_NW =			(-1, +1)
